name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  create-release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.2
    
    - name: Run tests before release
      run: php run_tests.php
    
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.ref_name }}
        name: Dungeon Crawler ${{ github.ref_name }}
        body: |
          ## Dungeon Crawler Game
          
          A text-based dungeon crawler game written in PHP for the Bundeling interview assignment.
          
          ### Features
          - Turn-based gameplay with 12 interconnected rooms
          - Combat system with 5 different monster types
          - Treasure collection and exploration
          - Comprehensive unit test suite (21 test cases)
          - Clean, maintainable code structure
          - GitHub Actions CI/CD pipeline
          
          ### Installation
          1. Clone this repository: `git clone https://github.com/zahrashahrooeii/dungeon-crawler.git`
          2. Navigate to the directory: `cd dungeon-crawler`
          3. Ensure PHP 7.0+ is installed
          4. Run: `php dungeon_crawler.php`
          
          ### Testing
          Run: `php run_tests.php`
          
          ### Requirements Met
          ✅ All core requirements implemented
          ✅ Optional enhancements included
          ✅ Clean code structure with separation of concerns
          ✅ Comprehensive testing
          ✅ CI/CD pipeline with automated testing
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
